services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    command: -p 5432
    expose:
      - 5432
    shm_size: 512mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: proxy_manager_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    env_file:
      - .env
    container_name: proxy_manager_app
    command: bash -c "cd .. && alembic upgrade head && cd src/ && python init_first_user.py && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:9000"
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    env_file:
      - .env
    container_name: celery_worker
    command: bash -c "celery --app=tasks.tasks:broker worker -l INFO -c '${TASKS}'"
    depends_on:
      - redis
      - app

  flower:
    build:
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    env_file:
      - .env
    container_name: celery_flower
    command: bash -c "celery --app=tasks.tasks:broker flower"
    ports:
      - "5555:5555"
    depends_on:
      - celery
      - redis
