"""empty message

Revision ID: 6277a3de6636
Revises: 7cb0645f760c
Create Date: 2024-08-25 02:27:18.653412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6277a3de6636'
down_revision: Union[str, None] = '7cb0645f760c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('proxy', sa.Column('latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'latency')
    op.drop_column('proxy', 'location')
    # ### end Alembic commands ###
