"""empty message

Revision ID: fa1d397fe2d2
Revises: 6277a3de6636
Create Date: 2024-08-25 02:36:46.005467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1d397fe2d2'
down_revision: Union[str, None] = '6277a3de6636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False, comment='bcrypt hashed password with salt'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment="Time when user's account expires"),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=False, comment='Future option'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
