"""empty message

Revision ID: 7cb0645f760c
Revises: 
Create Date: 2024-08-20 08:52:29.622004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb0645f760c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('port', sa.String(length=5), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('alive', 'dead', name='status'), nullable=True),
    sa.Column('socks4', sa.Boolean(), nullable=True),
    sa.Column('socks5', sa.Boolean(), nullable=True),
    sa.Column('http', sa.Boolean(), nullable=True),
    sa.Column('https', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proxy_ip_port_username_password', 'proxy', ['ip', 'port', 'username', 'password'], unique=True)
    op.create_index(op.f('ix_proxy_ip'), 'proxy', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_ip'), table_name='proxy')
    op.drop_index('idx_proxy_ip_port_username_password', table_name='proxy')
    op.drop_table('proxy')
    # ### end Alembic commands ###
